version: "2.4"

services:

  # # resources
  # # NSQ
  # nsqlookupd:
  #   image: nsqio/nsq:v1.2.1
  #   command: /nsqlookupd
  #   ports:
  #     - "4161:4161"

  # nsqd:
  #   image: nsqio/nsq:v1.2.1
  #   command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address nsqd --msg-timeout=15m0s
  #   depends_on:
  #     - nsqlookupd
  #   stop_signal: SIGTERM
  #   ports:
  #     - "4150:4150"
  #     - "4151:4151"

  # nsqadmin:
  #   image: nsqio/nsq
  #   command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
  #   depends_on:
  #     - nsqlookupd  
  #   ports:
  #     - "4171:4171"
  #   healthcheck:
  #     test: ["CMD-SHELL", "/usr/bin/wget -q -s http://0.0.0.0:4171/ping && exit 0 || exit 1"]


  # # Redis
  # redis:
  #   image: redis
  #   expose: 
  #     - 6379

  # Postgres
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data